# -*- coding: utf-8 -*-
"""health tips bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11FIKuLOSgtl7hr3KS6tzAXI8ExVSunwm
"""

!pip install --upgrade openai -q

import os
from openai import OpenAI

# ===== 1. PUT YOUR API KEY HERE =====
os.environ["OPENAI_API_KEY"] = "sk-...T_0A"   # ⬅️ Replace this
client = OpenAI(api_key=os.environ["sk-...T_0A"])

# ===== 2. SET UP THE HEALTH TIPS BOT =====
SYSTEM_MESSAGE = """
You are a friendly, supportive health and wellness tips assistant.

RULES (VERY IMPORTANT):
- You ONLY give general lifestyle and wellness tips (food, sleep, exercise, hydration, stress, habits).
- You are NOT a doctor and you are NOT giving medical advice.
- Do NOT diagnose diseases, do NOT suggest medications, doses, or treatments.
- If the user mentions serious symptoms, pain, or emergencies, tell them to contact a doctor or emergency services immediately.
- Always include a short disclaimer at the end like:
  "This is general wellness information only, not medical advice. Please talk to a doctor for any medical concerns."
- Be kind, simple, and encouraging.
"""

def ask_health_bot(user_message: str) -> str:
    """Send a message to the health tips bot and return the reply."""
    response = client.chat.completions.create(
        model="gpt-4.1-mini",   # You can change the model if you like
        messages=[
            {"role": "system", "content": SYSTEM_MESSAGE},
            {"role": "user", "content": user_message}
        ],
        temperature=0.7,        # creativity
        max_tokens=400
    )
    return response.choices[0].message.content

# ===== 3. SIMPLE CHAT LOOP =====
print("💚 Health Tips Bot")
print("Type your health/wellness question below.")
print("Type 'quit' or 'exit' to stop.\n")

while True:
    user_input = input("You: ").strip()
    if user_input.lower() in ["quit", "exit", "q"]:
        print("Bot: Take care of yourself! 🌿")
        break

    try:
        reply = ask_health_bot(user_input)
        print("\nBot:", reply, "\n")
    except Exception as e:
        print("Oops, something went wrong:", e)
        break